# Generated by Django 4.1 on 2023-03-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_alter_administrador_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='codigo',
            new_name='id',
        ),
    ]
