# Generated by Django 4.1 on 2023-03-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_rename_codigo_administrador_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='codigo',
            field=models.IntegerField(default=1, verbose_name='Codigo'),
            preserve_default=False,
        ),
    ]
