# Generated by Django 4.1.7 on 2023-03-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_alter_proveedor_id_alter_proveedor_nombre_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(max_length=10),
        ),
    ]
