# Generated by Django 4.1.7 on 2023-03-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0006_alter_proveedor_ruc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamento',
            name='Tipo',
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
